name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "*/30 * * * *" 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clean
      run: |
        README_TMP=readme.html
        curl -s https://github.com/${GITHUB_REPOSITORY}/blob/master/README.md > ${README_TMP}
        grep -Eo '<img src="[^"]+"' ${README_TMP} | grep camo | grep -Eo 'https[^"]+' | xargs -I {} curl -w "\n" -s -X PURGE {}

