name: Clean Camo Cache

on: 
  push:
  schedule:
    - cron: "0 0 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clean
      run: |
        README_TMP=readme.html
        curl -s https://github.com/${GITHUB_REPOSITORY}/blob/master/README.md > ${README_TMP}
        grep -Eo '<img src="[^"]+"' ${README_TMP} | grep camo | grep -Eo 'https[^"]+' | xargs -I {} curl -w "\n" -s -X PURGE {}

